name: CI/CD build & deploy

on:
  push:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload source as artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .

  setup-qemu:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

  setup-buildx:
    runs-on: ubuntu-latest
    needs: setup-qemu
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  docker-login:
    runs-on: ubuntu-latest
    needs: setup-buildx
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-push:
    runs-on: ubuntu-latest
    needs: docker-login
    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v4
        with:
          name: source-code
          path: .

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
            ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}

  # deploy-to-render:
  #   runs-on: ubuntu-latest
  #   needs: build-push
  #   steps:
  #     - name: Trigger Render Deploy Hook
  #       run: |
  #         curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
