name: CI/CD build & deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Set up QEMU (for multi-platform builds, optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4️⃣ Log in to Docker Hub using GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
            ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}

# deploy-to-render:
#   needs: build-and-push
#   runs-on: ubuntu-latest
#   steps:
#     - name: Trigger Render Deploy Hook
#       run: |
#         curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

